services:
  - type: web
    name: yomu-core-api
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GATEWAY_SHARED_SECRET
        sync: false
      - key: DATABASE_JDBC_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: RABBITMQ_HOST
        sync: false
      - key: RABBITMQ_PORT
        value: "5672"
      - key: RABBITMQ_USERNAME
        sync: false
      - key: RABBITMQ_PASSWORD
        sync: false
      - key: RABBITMQ_VHOST
        sync: false
